### PR TITLE
Update setenv.sh

### PR DESCRIPTION
**Pull request by jfabernathy**
change sdk version for default to match readme.md

### CODE REVIEW

**Comment by jfabernathy** [comment]
Made additional changes to readme.md

**Comment by bennettpeter** [comment]
As far as I can see, you changed the readme from 29.0.2 to 29.0.3 in your previous change, now you are complaining that the setenv does not match the readme. Before you changed the readme, both the readme and the setenv were 29.0.2.

Why the change from 29.0.2 to 29.0.3? The latest version is 33.0. We were staying on 29.0.2 until we were forced to change. If you think we should be more up to date, then why not 33.0? There are many versions of 30, 31 32 and 33.

I would prefer to leave it at 29.0.2 until some day we update it to the latest if possible.

**Comment by jfabernathy** [comment]
If you think it's right to leave setenv at 29.0.2, then please change the
Readme to 29.0.2.  Sorry I messed it up. Just trying to build android
mythfrontend.  I really don't know what I'm doing, but I know the previous
instructons didn't work. With everything set to 29.0.2 it should work.  I'm
out of town for a month, so I can't update the request.

**Comment by bennettpeter** [comment]
I have updated the readme to revert the instructions to 29.0.2.
Pull Request Rejected

**Pull request closed without merging**
