### PR TITLE
android docker configuration and build

### PR DESCRIPTION
**Pull request by IcoDeveloper**
bring android docker configuration into sync with recommended versions from wiki and add required python3 
fix libbluray compile error by updateing to newer version (1.1.2 to 1.3.4)

### CODE REVIEW

**Comment by IcoDeveloper** [comment]
Should also fix issue #155

**Comment by mspieth** [comment]
I assume you have tested the docker changes and they work

**Review by mspieth — APPROVED** [review]

**Review by mspieth — APPROVED** [review]

**Comment by mspieth** [comment]
Also for future change, it would be good to support the multiple configs in android-utilities/config in this dockerfile somehow.

**Comment by mspieth** [comment]
Also Readme.md should be updated too

**Pull request merged**
