### PR TITLE
Add libmysql++-dev to handle Debian Stretch

### PR DESCRIPTION
**Pull request by MikeB2013**
Debian 9  Stretch does not use libmysqlclient-dev it is replaced by libmysql++-dev

This may also need to be applied to other branches e.g. 0.28/fixes but I have only tested on master

I have created trac ticket for tracking (not sure if needed) 
https://code.mythtv.org/trac/ticket/13065

### CODE REVIEW

**Comment by superm1** [comment]
I'm kinda surprised this change has happened in Debian stretch but not carried over to Ubuntu Artful.  
Are you sure it's what's happened?  Putting that fix in I don't think is going to "really" fix the problem.

1. The artful builds were still using libmysqlclient-dev: https://launchpadlibrarian.net/323098591/buildlog_ubuntu-artful-amd64.mythtv_2%3A0.29.0~master.20170608.f593e23-0ubuntu0mythbuntu1_BUILDING.txt.gz

2. I still see `libmysqlclient-dev` on the `mysql-5.7` source package: https://tracker.debian.org/pkg/mysql-5.7 but that's only in unstable.

Actually I think that in stretch debian devs punted mysql server out on purpose, and want people using mariadb.
https://tracker.debian.org/pkg/mariadb-10.1

3. You're referring to this package https://tracker.debian.org/pkg/mysql++which hasn't been touched in a very long time.

**Comment by MikeB2013** [comment]
Yes, you are correct default database on Debian Stretch is mariadb.

It is quite possible my fix is the wrong one for a proper resolution.

I went back to a default Debian Stretch install and tried to build debs. 
The build failed as it could not find package libmysqlclient-dev, not surprising as it does not exist in Stretch, there is a package default-libmysqlclient-dev.
Here is console log:

[first-run-on-clean-stretch.txt](https://github.com/MythTV/packaging/files/1141348/first-run-on-clean-stretch.txt)

Here is the mythtv-build-deps .deb file (I had to zip it to upload)
[mythtv-build-deps.zip](https://github.com/MythTV/packaging/files/1141364/mythtv-build-deps.zip)

Mike

**Comment by MikeB2013** [comment]
Just checked mythtv ansible playbook at 
https://github.com/MythTV/ansible/blob/master/roles/mythtv-deb/tasks/main.yml

This was recently updated to use default-libmysqlclient-dev  so this appears to be the way forward.

**Comment by lwt-pressy** [comment]
fix worked on my stretch system 👍

**Comment by lwt-pressy** [comment]
any news on this pull @superm1 @tgm4883 ?

**Comment by tgm4883** [comment]
@lwt-pressy Sorry this took so long. Can you rebase that into a single commit and we'll get it merged.

**Comment by lwt-pressy** [comment]
@tgm4883: I not sure how to do it since it is @MikeB2013 request.

**Comment by MikeB2013** [comment]
Done as a single commit please see PR 70. Was not sure how to do the rebase into a single commit. Am closing this PR

**Pull request closed without merging**
