### PR TITLE
OSX packaging restructure and addition of macports_ansible script

### PR DESCRIPTION
**Pull request by jhoyt4**
This update restructures the OSX buils directory moving the depricated "osx-packager-qtsdk.pl" script and associated README.txt into a new directory.  Adding a new README.md file.

It also adds the "compileMythfrontendAnsible.zsh" script into the new "macports_ansible" directory which is currently being used to build Mythfrontend.app for the community.

### CODE REVIEW

**Comment by rcrdnalor** [comment]
The script `compileMythfrontendAnsible.zsh` has a switch
to select the python version (--python-version).

But the call to `./configure` of MythTV is done with a 
hard-coded python version: `--python=/opt/local/bin/python3.8`.
 
In other words, the user needs to have python3.8 installed at
'/opt/local/bin/python3.8'.

What are the shebangs of the python grabber scripts in
'/usr/share/mythtv/metadata/[Movie,Television,Music]' ?


Furthermore, I do not see where `$Python` is initialized in
'export PYTHONPATH="$INSTALL_DIR/lib/$PYTHON/site-packages"'.

**Comment by jhoyt4** [comment]
Good catch on the `--python=/opt/local/bin/python3.8` is a mistake left in and was meant to take the value from the switch.  I just submitted a fix to my repo to correct this.

As for `export PYTHONPATH="$INSTALL_DIR/lib/$PYTHON/site-packages"` - this was dead code and is now removed in my latest push.

I was trying to figure out why the compiled app didn't see the MythTV python module I copied into the app.  The PYTHONPATH script was in the old build script so I tried it to no avail.  The python issues are now resolved with this symlink ` ln -s python$PYTHON_DOT_VERS python2.6`.  I have a ticket open in trac to fix the real issue (hardcode in the mythtv code) [here in ticket 13643:](https://code.mythtv.org/trac/ticket/13643)

As for "share/mythtv/metadata/"  here is what is in there (BTW, as of my build this morning the python stuff is now working):
"find share/mythtv/metadata -print
share/mythtv/metadata
share/mythtv/metadata/Music
share/mythtv/metadata/Music/lyrics
share/mythtv/metadata/Music/lyrics/genius.py
share/mythtv/metadata/Music/lyrics/lyricsmode.py
share/mythtv/metadata/Music/lyrics/filelyrics.py
share/mythtv/metadata/Music/lyrics/darklyrics.py
share/mythtv/metadata/Music/lyrics/gomaudio.py
share/mythtv/metadata/Music/lyrics/alsong.py
share/mythtv/metadata/Music/lyrics/lyricswiki.py
share/mythtv/metadata/Music/lyrics/README
share/mythtv/metadata/Music/lyrics/common
share/mythtv/metadata/Music/lyrics/common/audiofile.py
share/mythtv/metadata/Music/lyrics/common/__init__.py
share/mythtv/metadata/Music/lyrics/common/.gitignore
share/mythtv/metadata/Music/lyrics/common/utilities.py
share/mythtv/metadata/Music/lyrics/embedlrc.py
share/mythtv/metadata/Music/lyrics/examples
share/mythtv/metadata/Music/lyrics/examples/taglyrics.mp3
share/mythtv/metadata/Music/lyrics/examples/README
share/mythtv/metadata/Music/lyrics/examples/filelyrics.mp3
share/mythtv/metadata/Music/lyrics/examples/filelyrics.lrc
share/mythtv/metadata/Music/lyrics/ttplayer.py
share/mythtv/metadata/Music/lyrics/lyricscom.py
share/mythtv/metadata/Music/lyrics/baidu.py
share/mythtv/metadata/Music/discid
share/mythtv/metadata/Music/discid/track.py
share/mythtv/metadata/Music/discid/util.py
share/mythtv/metadata/Music/discid/__init__.py
share/mythtv/metadata/Music/discid/README
share/mythtv/metadata/Music/discid/disc.py
share/mythtv/metadata/Music/discid/.gitignore
share/mythtv/metadata/Music/discid/libdiscid.py
share/mythtv/metadata/Music/musicbrainzngs
share/mythtv/metadata/Music/musicbrainzngs/compat.py
share/mythtv/metadata/Music/musicbrainzngs/util.py
share/mythtv/metadata/Music/musicbrainzngs/mbxml.py
share/mythtv/metadata/Music/musicbrainzngs/musicbrainz.py
share/mythtv/metadata/Music/musicbrainzngs/__init__.py
share/mythtv/metadata/Music/musicbrainzngs/README
share/mythtv/metadata/Music/musicbrainzngs/.gitignore
share/mythtv/metadata/Music/musicbrainzngs/caa.py
share/mythtv/metadata/Music/mbutils.py
share/mythtv/metadata/Movie
share/mythtv/metadata/Movie/tmdb3.py
share/mythtv/metadata/Television
share/mythtv/metadata/Television/ttvdb.py
share/mythtv/metadata/Television/tvdb_test.conf"

**Comment by billmeek** [comment]
@jhoyt4, #13643 was just updated. Removed a variable just used for my tests.

**Comment by jhoyt4** [comment]
@billmeek - sorry missed your note before compiling / testing.  I just submitted a patch file to #13643 that fixes the issue.

**Comment by jhoyt4** [comment]
I just pushed a new patch to my packaging repo which removes the python2.6 symbolic link hack.

@billmeek - thank you for the quick fix on ticket #13643

**Comment by billmeek** [comment]
John, re fd216c3

These should be executable in the source tree already. The rest are modules and needn't be.
Here's what's left in my host:
```
ls -ld ./mythplugins/mythgame/mythgame/scripts/giantbomb.py ./mythtv/programs/scripts/metadata/Music/mbutils.py ./mythtv/programs/scripts/metadata/Television/ttvdb.py ./mythtv/programs/scripts/metadata/Movie/tmdb3.py
-rwxrwxr-x 1 bill bill  13123 Nov 14  2019 ./mythplugins/mythgame/mythgame/scripts/giantbomb.py
-rwxrwxr-x 1 bill bill  13325 Jul  3 08:58 ./mythtv/programs/scripts/metadata/Movie/tmdb3.py
-rwxrwxr-x 1 bill bill  16368 Jul  3 08:58 ./mythtv/programs/scripts/metadata/Music/mbutils.py
-rwxrwxr-x 1 bill bill 138526 Jul 15 22:01 ./mythtv/programs/scripts/metadata/Television/ttvdb.py
```
The --preserve switch in the cp command may be enough. [Kindly recall that I don't speak OSX]

**Comment by jhoyt4** [comment]
Thanks Bill - I just checked the installed versions (INSTALL_DIR/share/mythtv/metadata)

And everything looks correctly set - I'll switch the cp over to use --preserve and back out the find / chmod.

**Pull request merged**
